version: "3.8"

services:
  ##### Proxy #####
  yarp:
    container_name: yarp_proxy
    build:
      context: ./CCProxy
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    env_file:
      - .env

  ##### API #####
  itemsapi:
    build:
      context: ./ItemsApi
      dockerfile: Dockerfile
    env_file:
      - .env

  consul:
    container_name: consul_service
    image: consul:1.8.4
    restart: unless-stopped
    ports:
      - "8500:8500" # HTTP API and UI port
    command: consul agent -dev -config-dir /etc/consul.d
    volumes:
      - ./consul.server.json:/etc/consul.d/consul.server.json

networks:
  default:
    name: yarp_proxy
    driver: bridge